# This is a basic workflow to help you get started with Actions

name: changelog-lint

# Controls when the workflow will run
on:
  pull_request:
    paths:
      - .changelog/*
      - CHANGELOG.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  changelog-lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version

      - name: install misspell
        run: cd .ci/tools && go install github.com/client9/misspell/cmd/misspell

      # Runs a set of commands using the runners shell
      - name: changelog-lint
        run: misspell -error -source text CHANGELOG.md .changelog