# This is a basic workflow to help you get started with Actions

name: golangci-lint

# Controls when the workflow will run
on:
  pull_request:
    paths:
      - tencentcloud/**
      - .github/**
      - .golangci.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  golangci-lint:
    # The type of runner that the job will run on
    runs-on: macos-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: list of changed files
        id: getDiffFile
        run: |
          echo "::set-output name=files::$(git diff --name-only origin/master | grep '\.go$' | xargs)"
        shell: bash

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
          #go-version: '1.21'
          cache: false 

      # Runs a set of commands using the runners shell
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          #version: v1.54
          working-directory: ./tencentcloud
          args: {{ steps.getDiffFile.outputs.files }} --new-from-rev=origin/master -v
          #args: --enable-all --max-same-issues=0 --max-issues-per-linter=0 --new-from-rev=origin/master -v
