name: Pull Request Labeler

on:
  # Triggers the workflow on pull request context
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
jobs:
  Labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Labels
        uses: andymckay/labeler@master
        with:
          remove-labels: "trigger_label_event"
          repo-token: ${{ secrets.MY_TOKEN }}

      - name: Apply Labels
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler-pr-triage.yml
          repo-token: ${{ secrets.MY_TOKEN }}
          sync-labels: true