# This is a sync code to tgit workflow

name: sync-code

on:
  push:
    branches:
      - master
      - 'coding-test/**'
      - 'pipeline/**'
    tags: v*

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        run: |
          if [ -d terraform-provider-tencentcloud ]; then
            rm -rf terraform-provider-tencentcloud
          fi
          git clone https://github.com/tencentcloudstack/terraform-provider-tencentcloud.git
      - name: sync
        run: |
          cd terraform-provider-tencentcloud
          git fetch --all
          git remote add tgit_origin https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@git.code.tencent.com/tencentcloudstack/terraform-provider-tencentcloud.git
          for remote in `git branch -r | grep -v "\->" | grep -v "master"`; do git branch --track ${remote#origin/} $remote; done
          git push -f --tags tgit_origin master:main
          git push -f --all tgit_origin
