name: workflow-lint
on:
  pull_request:
    paths:
      - .github/workflows/*
      - .ci/tools/go.mod
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 1.18.1
      - name: install actionlint
        run: cd .ci/tools && go install github.com/rhysd/actionlint/cmd/actionlint
      - name: actionlint
        run: actionlint -shellcheck=
